// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// baskets
export const BASKET_ADD_PRODUCT = 'BASKET_ADD_PRODUCT';
export const BASKET_REMOVE_PRODUCT = 'BASKET_REMOVE_PRODUCT';
export const BASKET_DROP_BASKET = 'BASKET_DROP_BASKET';

// sessions
export const SESSION_CREATE = 'SESSION_CREATE';
export const DISCARD_DESK = 'DISCARD_DESK';
